### PR TITLE
Allow pattern examples to be iFramed (and improve Rollup config)

### LINKED ISSUE #23: Allow iFraming of pattern previews
Sometimes patterns need to be iFramed to work correctly (they may be fixed position, or rely on breakpoints, for example.)

We should add an option in pattern frontmatter to iFrame specific patterns. We should use something like [iframe-resizer](https://www.npmjs.com/package/iframe-resizer) to make sure these are sized correctly.

### PR DESCRIPTION
**Pull request by Paul-Hebert**
Pattern examples can now be displayed in iFrames. The iFrames are resized to fit the pattern content. As part of this work there were a number of tasks:

- Add new iFrameExample option in Frontmatter
- Document option in READMEs
- Use option to determine whether an example is iFramed
- Write some basic iFrame CSS
- Show an example
- Use a new layout for iFramed examples
- Update the `pattern` task to set the correct layouts.
- Add the `iFrameResizer` library
- Configure the `iFrameResizer` library
- Add `node-resolve` and `commonjs` rollup plugins
- Make an example on `/patterns/pattern-example/` be iFramed

Fixes #23

### CODE REVIEW

**Comment by Paul-Hebert** [comment]
@tylersticka if you have time to review this that would be awesome,  but if not that's totally okay 🙂

**Comment by tylersticka** [comment]
@Paul-Hebert This is working great!

I'm not sure if this detail is too "in the weeds" or not, but for a recent project I added a pattern container class in a different place depending on whether or not the example was in an iframe. This was to avoid this situation, where the padding is applied _outside_ of the pattern:

Screen Shot 2019-12-17 at 2 13 29 PM

That said, I'm completely fine moving forward without solving this for now since we don't really have a final interface yet. Do you feel this is premature feedback at this stage?

**Comment by Paul-Hebert** [comment]
I don't think that's too in the weeds. I can update the PR to implement that. 😀

**Comment by Paul-Hebert** [comment]
@tylersticka , is this along the lines of what you were imagining?

https://github.com/cloudfour/eleventy-patterns/pull/28/commits/ce2ddd474561879ec4c660030c308f93ac057ba9

**Comment by tylersticka** [comment]
@Paul-Hebert Yes, exactly!

**Review by tylersticka — APPROVED** [review]

**Pull request merged**
