### PR TITLE
No merge/do not review

### PR DESCRIPTION
**Pull request by dromo77**
Some more nav explorations, generating a deploy preview.

### CODE REVIEW

**Comment by Paul-Hebert** [comment]
Thanks @dromo77 ! These are great iterations! I really like how this is coming along! I'm commenting here instead of responding to your Slack message to avoid pinging you outside of work hours.

### Initial Thoughts

I think all of these are steps in the right direction. The fixed sidebar is a nice touch, and I like the base styles you've begun to apply. 

If we do further iterations it may be helpful to stub out more patterns and prototypes, so we can get a feel for how these options work with a number of items. This could be done by running the `npx gulp prototype` and `npx gulp pattern` commands from the command line, copying and pasting folders, or just inserting some dummy HTML into the different sidebars. 

### Options 1 and 2

These are both really cool! I don't have strong feelings between the fixed header and the semi-sticky header. I think either could work well. I'm curious how the sidebar on large screens would feel as it slid up and down if you were using the site regularly. Do you have a preference on the header version?

### Option 3

Thanks for trying this out! I like that you can navigate to any page from any page. One thing I think may help is to expand the section you're currently visiting. For example, if you're viewing a pattern, the "Patterns" accordion in the sidebar would be open when the page loads.

### Final Thoughts

These are looking really good! I have a few nitpicks, but I think at this point we should settle on a direction before working on more refinement. 

The primary difference between the first two options and option 3 seems to hinge on whether we need a separate top nav in addition to the sidebar (on large screens.) I'm leaning towards only having a sidebar, but I can see some arguments for and against that.

#### Simplicity

I think having one nav section is simpler than 2, but I think accordions add more UX complexity than simple links. That said, using accordions would be consistent between screen sizes. It may be a toss-up about which option is simpler to understand. 

#### Speed of navigation

Either way we go, navigating to a link in the same category will take 1 click, and navigating to a link in a different category will take 2 (on large screens.) 

However, the top nav requires a full page load to view another category's items, and be able to navigate to them. Because of this, it seems like it would be quicker to navigate with the accordions, as they require less full page loads.

#### Your Thoughts

I know you've spent a lot more time working through this problem so I'm curious what you think about these options?

1. Are there other options you would like to explore before further refining one of these options?
2. Is there a specific option you prefer? If so, why?
3. Are there pros and cons of the accordion option I'm not seeing?
4. Are there pros and cons of the top nav options I'm not seeing?
5. When using a top nav, do you prefer the fixed header or the semi-sticky header?


#### Next Steps

When you have a chance, please take a moment to respond to the questions above, as well as ask me questions or address anything I've missed. I think we should use these questions as an opportunity for us to weigh the pros and cons of the different options, and settle on a direction to refine. I'm leaning towards option 3, but I think any option could work, and am curious what you think.

Once we've landed on a direction we can refine it and use it to update this boilerplate! Thanks again for all the great work on this!

**Comment by dromo77** [comment]
Thanks for the great feedback! Here are some of my thoughts, hopefully this helps to narrow it down to one solution.

1. I'm pretty happy with the overall direction of these explorations, I don’t want to throw any brand new ideas into the mix. I think picking a direction and working on refining it is the way to go.

2. I'm not tied to a specific solution. I think option 3 has some benefits over the others. 

- It has the same navigation behavior on small and large screens so you don’t have to learn different ways of navigating. 
- As you mentioned, less full page loads
- I also like that the accordion keeps the categories/links grouped together visually. 

From a less objective standpoint, I really like that options 1 and 2 push the navigation in a different direction than the current Drizzle solution 😅 

3. I wanted to give a quick summary of the pros and cons. I think we’ve talked about most of them, but I think it helps to see them listed out.

**Pros:**
* Consistency across screen sizes
* Strong association between categories and links
* Speed of navigation, the accordions require less full page loads
* All navigation items are accessible on any given page

**Cons:**
* More complex UX
* We may decide to incorporate some kind of auto closing behavior, but right now multiple accordions can be open at one time.  If multiple accordions are open at once, the menu could start to get really long and feel similar to the current solution.

4. Pros and cons for the split navigation:

**Pros:**
* Less complex UX
* Only relevant links are shown on large screens. This is good and bad, it means there’s less content to digest. However, it also means  you have to navigate to a new page( requiring a  full page load) to view another category’s items.

**Cons:**
* Mentioned above, top level nav requires a full page load to view another category’s items.

5. I could go either way. I like that the semi sticky behavior doesn’t take up as much space on smaller screens. However, as you pointed out, I’m not sure how I feel about the interaction with the sidebar on large screens. If we move forward with option 1 or 2, I think it would be worth exploring further.

Overall I think there are some clear benefits to option 3, however I have some questions about the behavior of the accordions whereas the other solution seems pretty straight forward.

**Comment by tylersticka** [comment]
Thinking about the amount of content we end up having in prototypes and patterns, I can't help but feel _significant_ misgivings about Option 3. It's not that it isn't _different_ (that would be silly), it's that it isn't solving any of the problems our current solutions have: The larger a project gets, the less people scroll down to see whatever stuff is getting pushed out of the way. Watching our clients use the current UI, it's clear that it's a real chore.

I like the nav that hides as you scroll: Having it fixed all the time feels unnecessary to me.

**Comment by dromo77** [comment]
Thanks @tylersticka, I was trying to say something similar in one of my bullet points about the cons, but you summed it up nicely.

**Comment by Paul-Hebert** [comment]
Awesome, thank you both @dromo77 , and @tylersticka !

>The larger a project gets, the less people scroll down to see whatever stuff is getting pushed out of the way. Watching our clients use the current UI, it's clear that it's a real chore.

>If multiple accordions are open at once, the menu could start to get really long and feel similar to the current solution.

These are important points. If one category had enough items, then that accordion being open would push other content off screen. The experience with clients really speaks to this as an issue as well.

>I like the nav that hides as you scroll: Having it fixed all the time feels unnecessary to me.

This  sounds good to me. It sounds like the overall consensus is we should move forward with [option 2](https://deploy-preview-41--eleventy-patterns.netlify.com/).

@dromo77 I think this option is looking really good. I have a few nitpicks as we work towards refining this further. (These are based on interacting with the prototypes, not looking at code changes.)

### Nits

1. **Link Touch Targets** — Some of the nav links could be a little difficult to click or tap. Ideally we'd be aiming for our links to be [equal to or larger than 44px x 44px](https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/). I think this could be achieved by adding vertical padding to these links. Sidebar links should also be full width (`display: block;`).
2. **Buttons and Cursors** — I know there's some debate about whether buttons should get `cursor: pointer;` but I'd lean towards using that on the menu button and accordions, since I think people have come to expect it.
3. **Colors Contrast** — I _really_ like the colors you've chosen, but I wonder if we could maintain a similar feel while increasing the contrast a little? Right now the sidebar links and labels are passing WCAG's AA specification, but if we could pass AAA that would be great.
4. **Home Page Margins** — It looks like the home page content lost its margins. I think it's probably related to one of our stagger CSS classes.
5. **Sticky Header Behavior** — I know you mentioned this was a WIP. If it would be helpful I could point you to some resources on how we handled that in previous projects.

### Next Steps

I'm excited that we've settled on a direction, and I think it's looking great! 

@dromo77 , would you like to work on further refining this further design-wise? I think it's looking _great_, besides the nits mentioned above but am curious if there are other changes you or @tylersticka would like to see before final implementation.

Once we've finished refining the design we can do the final dev implementation. @dromo77 , would you like to run point on that or would you appreciate some dev help there?

Thanks for all the great work on this! This will be a big improvement to this tool!

**Comment by Paul-Hebert** [comment]
@derekshirk , I just saw you had some great feedback on this in Slack as well! Sorry to fragment the conversation. I posted here to avoid pinging people on Slack in the middle of  the night (since I'm in a different time zone) but I didn't mean to leave you out of this discussion. 

You raised some great points in Slack! Thanks for sharing your expertise! Feel free to chime in here as well if you've got more feedback. I'll be sure to tag you if we end up having further discussion in GitHub. 🙂

**Comment by dromo77** [comment]
That sounds good @Paul-Hebert . I'll move forward with option 2 and address the nits you pointed out. If you have resources for the sticky header you can share that would be helpful. Hopefully that will address the "janky" behavior Derek brought up in slack.

Once the refinements have been worked out, I would definitely appreciate your help with the dev implementation.

**Comment by Paul-Hebert** [comment]
Thanks @dromo77 ! Sorry for the slow response. I was out sick yesterday. 

---

At a quick glance there are a few things that could be making the sticky header feel janky:

1. The sidebar content should have the same transition as the nav's transition so they slide together.
2. Transitioning `top` and `margin-top` requires the browser to re-perform the layout step which can be expensive and slow. [Transitioning `transform`s is more performant and feels smoother](https://medium.com/outsystems-experts/how-to-achieve-60-fps-animations-with-css3-db7b98610108).
3. It's possible to get stuck in a loop where the header is shown and hidden over and over again when the page is barely taller than the viewport (try scrolling down on the Pattern Example page, in a full height window on your laptop)
4. `scroll` event listeners can fire rapidly, calling your JS code over and over again. This can lead to the browser getting bogged down and slowing. You generally want to [throttle or debounce](https://blog.bitsrc.io/understanding-throttling-and-debouncing-973131c1ba07) scroll event listeners to avoid this. When we worked on this last I found that debounce worked better than throttle in this case. (This would likely fix point 3 as well)

---

Here's how we implemented this on a recent project:

We started off with the [Headsup.js](https://github.com/ChrisCavs/headsup.js) open source project. This did most of what we wanted, but didn't quite fit our needs, so we created a [Cloud Four fork](https://github.com/cloudfour/headsup.js/).

You can install this from the command line like so: `npm i github:cloudfour/headsup.js#5e2059a`

Then you can do the following in your JS file:

```js
import headsUp from 'headsup.js'

headsUp({
  selector: '.EP_nav',
  debounce: 100,
  hiddenHeaderClass = 'EP-nav-hidden'
});
```

That should get you up and running JS-wise, and fix points 3 and 4 above. You could then do something like this with your CSS to fix points 1 and 2:

```css
.EP_nav, 
.EP_sidebar__menu {
  transition: transform var(--transition-quick);
}

.EP-nav-hidden .EP_nav, 
.EP-nav-hidden .EP_sidebar__menu {
  transform: translateY(calc(var(--EP_nav-height) * -1));
}
```

---

Hopefully that's helpful! Let me know if any of it doesn't make sense, or if you run into any issues.

**Comment by dromo77** [comment]
Thanks @Paul-Hebert, that info was super helpful! Using headsup will be a huge improvement 🙂.

**Pull request closed without merging**
